### ISSUE TITLE
Question about applying pose imitator for pose estimator step

### ISSUE THREAD

**Issue by SonNguyen2510** [Garfield-kh/PoseTriplet#20]
Dear author,

Thank you for your amazing work.
Currently I'm learning about 3D pose estimation and I'm really impressed by your work. As I understand so far, your pose estimator_inference step (when test with videos) doesn't apply pose imitator. Could you tell me the reason why you dont apply it?
And if I want to apply the imitator, can you tell me how can I do it? Sorry I am new to this pose estimation field.
Thank you so much for your time.

**Comment by Garfield-kh** [comment]
Thank you for the interest!
The core idea of this frame is: 
**(A).** the estimator converts 2D poses to implausible 3D motion, 
**(B).** the imitator generate plausible 3D motion by adding physical correction, 
**(C).** the hallucinator acts as a generator to diversify the motion.
If you want to apply the imiator for in the wild case, you may replace the H36M reference motion of (**A**) by in-the-wild result, then apply imitator (**B**) with pretrained weight, or finetune it with some iteration (e.g. 100 iter) for better fitting.

In detail:
The **first** thing is prepare a pre-trained imitator weight, this can be done by 
**step a**: download the [checkpoint folder](https://drive.google.com/drive/folders/1iGh1Sk30Tg8-UgGXM_8KwTQSbh7jcW9Y?usp=sharing) here, which contain reference motion in each round, (the imitator weight is not provide here because the process of export data out from server is too complicated). 
**step b**: Take the last round and train the imitator from [line 268](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L268) to [line 276](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L276) in script.

The second thing is prepare reference motion, this can be done by:
**step a**: use the [estimator_inference](https://github.com/Garfield-kh/PoseTriplet/blob/main/estimator_inference/videopose-j16-wild-eval_run.py) save a pickle file in joint-xyz format pickle file.
**step b**: replace the varible H36M motion `predicted_3d_wpos_withroot` at [line 318](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L318) by the in-the-wild motion.
**step c**: change the `takes` at [line 336](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L336) to the number of video you want to imitate. The original 600 is H36M with 600 clip.
**step d**: change the configuration file of imitator from H36M to yours, and run something similar from [line 268](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L268) to [line 273](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L273) to prepare the in-the-wild motion reference trajectory.

The third thing is try imitator on the in-the-wild reference motion:
**step a**: try the [imitator inference at line 278](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L278) directly, 
**step b**: or finetune it use [line 276](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L276) with `--iter 6000` to finetune it.

hope this helps. :)

**Comment by SonNguyen2510** [comment]
Thank you so much for your detail explaination!

**Comment by Dong09** [comment]
> Thank you so much for your detail explaination! 
> 

hello,thank you for your work first. I'm new to this. i got itr6000 pkl directly using helix5 training commands in the script , and i'm wondering how i can physically optimize my own wild video. i would appreciate your reply.
