### ISSUE TITLE
How to project the predicted 3D pose to the 2D pose

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#29]
Hi, I want to project the predicted 3D pose to the 2D pose to see the difference between this 2D pose and the 2D pose from which the 3D pose is derived of. I wonder whether it is right that I use the method project_to_2d(X, camera_params) of camera.py with the real parameters of the camera that took the images because the real camera parameters were not used in training. How to project the predicted 3D pose to the 2D pose? Thank you.

**Comment by Garfield-kh** [comment]
Hi, there is a term called reprojection loss, is that what you saying?

**Comment by bingbing-li** [comment]
Hi,
Please correct me if I am wrong.
You want to use the function project_to_2d() to project your predicted 3D poses to 2D poses, and then compare with GT 2D?

Yes you may proceed with the method. Basically it is using the pin-hole camera model to project 16 points.

From: gyou2021 ***@***.***>
Sent: 2022年11月1日 17:39
To: Garfield-kh/PoseTriplet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Garfield-kh/PoseTriplet] How to project the predicted 3D pose to the 2D pose (Issue #29)


Hi, I want to project the predicted 3D pose to the 2D pose to see the difference between this 2D pose and the 2D pose from which the 3D pose is derived of. I wonder whether it is right that I use the method project_to_2d(X, camera_params) of camera.py with the real parameters of the camera that took the images because the real camera parameters were not used in training. How to project the predicted 3D pose to the 2D pose? Thank you.

**Comment by gyou2021** [comment]
> Hi, there is a term called reprojection loss, is that what you saying?

Yes. Where or how to get the camera parameters to calculate project_to_2D(X, camera_param) where X is 3D pose? Thank you.

**Comment by gyou2021** [comment]
> Hi, Please correct me if I am wrong. You want to use the function project_to_2d() to project your predicted 3D poses to 2D poses, and then compare with GT 2D? Yes you may proceed with the method. Basically it is using the pin-hole camera model to project 16 points. 

Yes. Is it right that I use the real camera parameters in the project_to_2d()? The real camera is the camera that takes images. Thank you.
